[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "aoc_2021_01"
path = "2021/01/solver.rs"

[[bin]]
name = "aoc_2021_02"
path = "2021/02/solver.rs"

[[bin]]
name = "aoc_2022_01"
path = "2022/01/solver.rs"

[[bin]]
name = "aoc_2022_02"
path = "2022/02/solver.rs"

[[bin]]
name = "aoc_2022_03"
path = "2022/03/solver.rs"

[dependencies]
aoc_lib = { path = "commons/rust/" }
strum = "0.24"
strum_macros = "0.24"
