[package]
name = "aoc_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
fxhash = "0.2.1"
itertools = "0.12.1"
priority-queue = "1.3.2"
strum = "0.26.1"
strum_macros = "0.26.1"
tempfile = "3.9.0"

[dependencies.clap]
version = "4.4.18"
features = [ "derive",]
