[package]
name = "aoc_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
fxhash = "0.2.1"
itertools = "0.12.1"
priority-queue = "1.4.0"
strum = "0.26.1"
strum_macros = "0.26.1"
tempfile = "3.10.0"

[dependencies.clap]
version = "4.5.0"
features = [ "derive",]
