[package]
name = "aoc_lib"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
itertools = "0.12.0"
strum = "0.25"
strum_macros = "0.25"

[dependencies.clap]
version = "4.4.12"
features = [ "derive",]
